-- AlterTable
ALTER TABLE "quotations" ADD COLUMN     "salesRepId" TEXT;

-- CreateIndex
CREATE INDEX "quotations_salesRepId_idx" ON "quotations"("salesRepId");

-- AddForeignKey
ALTER TABLE "quotations" ADD CONSTRAINT "quotations_salesRepId_fkey" FOREIGN KEY ("salesRepId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================================
-- Backfill (manual, not auto-generated by prisma migrate)
-- ============================================================================
-- Copy `createdById` → `salesRepId` for every existing row so the
-- new field is populated for historical quotations. Safe to run
-- after the FK is in place because `createdById` has been NOT NULL
-- since Day 1, so every user id referenced is known to exist.
--
-- Going forward, the API defaults `salesRepId` to the authenticated
-- user on create when omitted, so newly-created rows are never null
-- unless explicitly cleared.
-- ============================================================================
UPDATE "quotations" SET "salesRepId" = "createdById" WHERE "salesRepId" IS NULL;