-- Migration: day7_extend_audit_action_enum
-- Extend AuditAction enum to include ROLE_*, SERVICE_*, PRODUCT_* values

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ROLE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ROLE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ROLE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SERVICE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SERVICE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SERVICE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_DELETED';
